---
- name: declare a variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access a varible
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable at another file level
  hosts: all
  connection: local
  vars_files:
    - Var.yml
  tasks:
    - name: access a varible
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable at inv file
  hosts: all
  connection: local
  tasks:
    - name: access a varible in inv file
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable at task level
  hosts: all
  connection: local
  tasks:
    - name: declare a varible and access
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: play.example.com

- name: ansible fact var
  hosts: all
  connection: local
  tasks:
    - name: ansible fact varible and access
      ansible.builtin.debug:
        msg: ansible host name == {{ansible_fqdn}}

- name: regaster a varable
  hosts: all
  connection: local
  tasks:
    - name: run ashell script
      ansible.builtin.shell: uptime
      register: out
    - name: print out var
      ansible.builtin.debug:
        msg: "{{out}}"
