---
- name: declare a variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access a varible
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declare a variable at task level
  hosts: all
  connection: local
  tasks:
    - name: declare a varible and access
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
        URL: play.example.com